import type {
  Run,
  EventEntry,
  Worker,
  MCPServer,
  ErrorGroup,
  RejectionCounts,
  RuntimeInfo,
  FlatRun,
} from "./types";

export const RUNS: Run[] = [
  {
    trace_id: "8c4a2f9b-ce11-4d3a-9e72-4b1f8a3d2c01",
    agent_name: "code-reviewer",
    parent_trace_id: null,
    depth: 0,
    status: "running",
    trust_level: "high",
    backend: "thread",
    tokens_used: 14820,
    duration_ms: 23410,
    started_at: "14:32:08",
    rejection_reason: null,
    error: null,
    task_input:
      "Review PR #4821: 'Add HMAC envelope signing to broker dispatch'. Run static analysis, security audit, doc lint, and test coverage check. Summarize findings.",
    task_metadata: { pr_number: 4821, repo: "murmur-core", author: "k.tanaka", base_branch: "main" },
    children: [
      {
        trace_id: "8c4a2f9b-ce11-4d3a-9e72-aa2f1d8b4101",
        agent_name: "static-analyzer",
        parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-4b1f8a3d2c01",
        depth: 1,
        status: "completed",
        trust_level: "high",
        backend: "thread",
        tokens_used: 3210,
        duration_ms: 4120,
        cascade_label: "single",
        children: [],
      },
      {
        trace_id: "8c4a2f9b-ce11-4d3a-9e72-bb3f2e9c5202",
        agent_name: "security-auditor",
        parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-4b1f8a3d2c01",
        depth: 1,
        status: "running",
        trust_level: "medium",
        backend: "job",
        tokens_used: 5840,
        duration_ms: 8920,
        cascade_label: "single",
        children: [
          {
            trace_id: "8c4a2f9b-ce11-4d3a-9e72-cc4f3fad6303",
            agent_name: "cve-checker",
            parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-bb3f2e9c5202",
            depth: 2,
            status: "completed",
            trust_level: "medium",
            backend: "job",
            tokens_used: 1820,
            duration_ms: 2110,
            cascade_label: "gather:3",
            children: [],
          },
          {
            trace_id: "8c4a2f9b-ce11-4d3a-9e72-dd5f40be7404",
            agent_name: "secret-scanner",
            parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-bb3f2e9c5202",
            depth: 2,
            status: "completed",
            trust_level: "medium",
            backend: "job",
            tokens_used: 940,
            duration_ms: 1830,
            cascade_label: "gather:3",
            children: [],
          },
          {
            trace_id: "8c4a2f9b-ce11-4d3a-9e72-ee6f51cf8505",
            agent_name: "policy-linter",
            parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-bb3f2e9c5202",
            depth: 2,
            status: "running",
            trust_level: "low",
            backend: "job",
            tokens_used: 1280,
            duration_ms: 3940,
            cascade_label: "gather:3",
            children: [],
          },
        ],
      },
      {
        trace_id: "8c4a2f9b-ce11-4d3a-9e72-ff7f62d09606",
        agent_name: "test-writer",
        parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-4b1f8a3d2c01",
        depth: 1,
        status: "completed",
        trust_level: "high",
        backend: "thread",
        tokens_used: 4210,
        duration_ms: 6840,
        cascade_label: "single",
        children: [],
      },
      {
        trace_id: "8c4a2f9b-ce11-4d3a-9e72-0a8073e1a707",
        agent_name: "doc-summarizer",
        parent_trace_id: "8c4a2f9b-ce11-4d3a-9e72-4b1f8a3d2c01",
        depth: 1,
        status: "spawned",
        trust_level: "low",
        backend: "thread",
        tokens_used: 0,
        duration_ms: 0,
        cascade_label: "single",
        children: [],
      },
    ],
  },
  {
    trace_id: "f1e2d3c4-b5a6-4798-89aa-bcdef0123456",
    agent_name: "claim-router",
    parent_trace_id: null,
    depth: 0,
    status: "running",
    trust_level: "medium",
    backend: "thread",
    tokens_used: 9120,
    duration_ms: 14280,
    started_at: "14:33:51",
    rejection_reason: null,
    error: null,
    task_input:
      "Triage incoming claims batch (n=240) by severity and route to appropriate handler agents.",
    task_metadata: { batch_id: "claims-2026-05-03-A", batch_size: 240 },
    children: [
      {
        trace_id: "f1e2d3c4-b5a6-4798-89aa-aaaa11111111",
        agent_name: "claim-triage",
        parent_trace_id: "f1e2d3c4-b5a6-4798-89aa-bcdef0123456",
        depth: 1,
        status: "completed",
        trust_level: "medium",
        backend: "thread",
        tokens_used: 6240,
        duration_ms: 9120,
        cascade_label: "single",
        children: [
          {
            trace_id: "f1e2d3c4-b5a6-4798-89aa-bbbb22222222",
            agent_name: "fraud-scorer",
            parent_trace_id: "f1e2d3c4-b5a6-4798-89aa-aaaa11111111",
            depth: 2,
            status: "completed",
            trust_level: "medium",
            backend: "job",
            tokens_used: 2120,
            duration_ms: 3410,
            cascade_label: "single",
            children: [
              {
                trace_id: "f1e2d3c4-b5a6-4798-89aa-cccc33333333",
                agent_name: "claim-router",
                parent_trace_id: "f1e2d3c4-b5a6-4798-89aa-bbbb22222222",
                depth: 3,
                status: "rejected",
                trust_level: "medium",
                backend: "thread",
                tokens_used: 0,
                duration_ms: 0,
                cascade_label: "single",
                rejection_reason: "cycle",
                error:
                  "SpawnCycleError: claim-router already in ancestor chain [claim-router → claim-triage → fraud-scorer → claim-router]",
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    trace_id: "3a7b9c2d-1e4f-4567-8910-abc1234567de",
    agent_name: "ingest-router",
    parent_trace_id: null,
    depth: 0,
    status: "running",
    trust_level: "high",
    backend: "job",
    tokens_used: 41280,
    duration_ms: 48910,
    started_at: "14:28:14",
    rejection_reason: null,
    error: null,
    task_input:
      "Batch-ingest documents from queue 'q-ledger-2026-05', extract entities, reconcile against ledger.",
    task_metadata: { queue: "q-ledger-2026-05", document_count: 1820 },
    children: [
      {
        trace_id: "3a7b9c2d-1e4f-4567-8910-aaaaaaaa1001",
        agent_name: "doc-extractor",
        parent_trace_id: "3a7b9c2d-1e4f-4567-8910-abc1234567de",
        depth: 1,
        status: "completed",
        trust_level: "high",
        backend: "job",
        tokens_used: 18420,
        duration_ms: 21340,
        cascade_label: "gather:4",
        children: [],
      },
      {
        trace_id: "3a7b9c2d-1e4f-4567-8910-bbbbbbbb2002",
        agent_name: "entity-resolver",
        parent_trace_id: "3a7b9c2d-1e4f-4567-8910-abc1234567de",
        depth: 1,
        status: "completed",
        trust_level: "high",
        backend: "job",
        tokens_used: 12840,
        duration_ms: 18230,
        cascade_label: "gather:4",
        children: [],
      },
      {
        trace_id: "3a7b9c2d-1e4f-4567-8910-cccccccc3003",
        agent_name: "ledger-reconciler",
        parent_trace_id: "3a7b9c2d-1e4f-4567-8910-abc1234567de",
        depth: 1,
        status: "running",
        trust_level: "high",
        backend: "job",
        tokens_used: 9120,
        duration_ms: 11210,
        cascade_label: "gather:4",
        children: [],
      },
      {
        trace_id: "3a7b9c2d-1e4f-4567-8910-dddddddd4004",
        agent_name: "audit-emitter",
        parent_trace_id: "3a7b9c2d-1e4f-4567-8910-abc1234567de",
        depth: 1,
        status: "rejected",
        trust_level: "sandbox",
        backend: "job",
        tokens_used: 0,
        duration_ms: 0,
        cascade_label: "gather:4",
        rejection_reason: "budget",
        error:
          "BudgetExceededError: spawn would consume ~3,200 tokens; runtime budget remaining 2,140",
        children: [],
      },
    ],
  },
  {
    trace_id: "0d1e2f30-4152-6374-8596-a7b8c9d0e1f2",
    agent_name: "code-reviewer",
    parent_trace_id: null,
    depth: 0,
    status: "completed",
    trust_level: "high",
    backend: "thread",
    tokens_used: 22140,
    duration_ms: 38420,
    started_at: "14:18:42",
    rejection_reason: null,
    error: null,
    task_input: "Review PR #4818: 'Refactor SSE backpressure handling'.",
    task_metadata: { pr_number: 4818, repo: "murmur-core" },
    children: [],
  },
  {
    trace_id: "9f8e7d6c-5b4a-3928-1706-fedcba987654",
    agent_name: "doc-summarizer",
    parent_trace_id: null,
    depth: 0,
    status: "failed",
    trust_level: "low",
    backend: "thread",
    tokens_used: 1840,
    duration_ms: 2910,
    started_at: "14:15:09",
    rejection_reason: null,
    error:
      "ToolExecutionError: fetch_url failed: HTTPError 503 from https://docs.internal/api/v2/...",
    task_input:
      "Summarize internal docs at https://docs.internal/api/v2/observability for new SRE onboarding.",
    task_metadata: {},
    children: [],
  },
  {
    trace_id: "5e4d3c2b-1a09-8877-6655-443322110099",
    agent_name: "security-auditor",
    parent_trace_id: null,
    depth: 0,
    status: "completed",
    trust_level: "medium",
    backend: "job",
    tokens_used: 8420,
    duration_ms: 14280,
    started_at: "14:09:33",
    rejection_reason: null,
    error: null,
    task_input: "Weekly dependency CVE sweep across all murmur-* repos.",
    task_metadata: {},
    children: [],
  },
];

export function flattenRuns(roots: Run[]): FlatRun[] {
  const out: FlatRun[] = [];
  function walk(node: Run, parentName: string | null): void {
    out.push({ ...node, parent_agent: parentName });
    (node.children || []).forEach((c) => walk(c, node.agent_name));
  }
  roots.forEach((r) => walk(r, null));
  return out;
}

export const ALL_RUNS_FLAT: FlatRun[] = flattenRuns(RUNS);

export const EVENT_STREAM: EventEntry[] = [
  { ts: "14:32:31.842", type: "tool_call_completed", agent: "static-analyzer", trace: "8c4a...4101", severity: "info", preview: "ruff_check → 0 errors, 4 warnings (4.12s)" },
  { ts: "14:32:31.711", type: "agent_completed", agent: "static-analyzer", trace: "8c4a...4101", severity: "info", preview: "output={status:'pass', findings:4}" },
  { ts: "14:32:30.918", type: "tool_call_started", agent: "policy-linter", trace: "8c4a...8505", severity: "info", preview: "check_policy(ruleset='broker-v2', file='envelope.py')" },
  { ts: "14:32:30.421", type: "agent_completed", agent: "secret-scanner", trace: "8c4a...7404", severity: "info", preview: "output={leaked:false, scanned:142}" },
  { ts: "14:32:30.220", type: "agent_completed", agent: "cve-checker", trace: "8c4a...6303", severity: "info", preview: "output={cves:[],deps_scanned:84}" },
  { ts: "14:32:29.844", type: "agent_spawned", agent: "policy-linter", trace: "8c4a...8505", severity: "info", preview: "backend=job trust=low parent=security-auditor" },
  { ts: "14:32:29.701", type: "agent_spawned", agent: "secret-scanner", trace: "8c4a...7404", severity: "info", preview: "backend=job trust=medium parent=security-auditor" },
  { ts: "14:32:29.642", type: "agent_spawned", agent: "cve-checker", trace: "8c4a...6303", severity: "info", preview: "backend=job trust=medium parent=security-auditor" },
  { ts: "14:32:28.301", type: "tool_call_completed", agent: "security-auditor", trace: "8c4a...5202", severity: "info", preview: "list_dependencies → 84 packages (1.21s)" },
  { ts: "14:32:24.118", type: "agent_spawned", agent: "test-writer", trace: "8c4a...9606", severity: "info", preview: "backend=thread trust=high parent=code-reviewer" },
  { ts: "14:32:23.910", type: "agent_spawned", agent: "security-auditor", trace: "8c4a...5202", severity: "info", preview: "backend=job trust=medium parent=code-reviewer" },
  { ts: "14:32:21.144", type: "agent_spawned", agent: "static-analyzer", trace: "8c4a...4101", severity: "info", preview: "backend=thread trust=high parent=code-reviewer" },
  { ts: "14:32:14.422", type: "spawn_rejected", agent: "claim-router", trace: "f1e2...3333", severity: "warn", preview: "reason=cycle ancestors=[claim-router,claim-triage,fraud-scorer]" },
  { ts: "14:32:08.018", type: "agent_spawned", agent: "code-reviewer", trace: "8c4a...2c01", severity: "info", preview: "backend=thread trust=high (top-level run)" },
  { ts: "14:31:42.221", type: "spawn_rejected", agent: "audit-emitter", trace: "3a7b...4004", severity: "error", preview: "reason=budget needed≈3200 remaining=2140" },
  { ts: "14:31:38.910", type: "tool_call_failed", agent: "doc-summarizer", trace: "9f8e...7654", severity: "error", preview: "fetch_url → HTTPError 503 (2.91s)" },
  { ts: "14:31:08.142", type: "agent_completed", agent: "doc-extractor", trace: "3a7b...1001", severity: "info", preview: "output={extracted:1820}" },
  { ts: "14:31:02.418", type: "tool_call_started", agent: "ledger-reconciler", trace: "3a7b...3003", severity: "info", preview: "reconcile_batch(period='2026-05')" },
  { ts: "14:30:48.110", type: "agent_completed", agent: "entity-resolver", trace: "3a7b...2002", severity: "info", preview: "output={entities:312, unresolved:8}" },
  { ts: "14:30:21.840", type: "agent_spawned", agent: "claim-router", trace: "f1e2...3456", severity: "info", preview: "backend=thread trust=medium (top-level)" },
];

export const WORKERS: Worker[] = [
  { id: "wkr-na-east-01", broker: "kafka://prod.kafka:9092", subscribed: ["code-reviewer", "test-writer", "doc-summarizer"], concurrency: 16, in_flight: 11, last_hb: "2s ago", status: "healthy" },
  { id: "wkr-na-east-02", broker: "kafka://prod.kafka:9092", subscribed: ["security-auditor", "cve-checker", "secret-scanner"], concurrency: 12, in_flight: 8, last_hb: "1s ago", status: "healthy" },
  { id: "wkr-na-east-03", broker: "kafka://prod.kafka:9092", subscribed: ["ingest-router", "doc-extractor", "entity-resolver"], concurrency: 24, in_flight: 18, last_hb: "3s ago", status: "healthy" },
  { id: "wkr-eu-west-01", broker: "kafka://prod.kafka:9092", subscribed: ["claim-triage", "fraud-scorer", "ledger-reconciler"], concurrency: 16, in_flight: 4, last_hb: "1s ago", status: "healthy" },
  { id: "wkr-eu-west-02", broker: "kafka://prod.kafka:9092", subscribed: ["policy-linter", "audit-emitter"], concurrency: 8, in_flight: 0, last_hb: "47s ago", status: "stale" },
];

export const MCP_SERVERS: MCPServer[] = [
  { name: "filesystem-mcp", mode: "stdio", tools_count: 6, tools: ["read_file","write_file","list_dir","search","stat","copy"], eager: true, status: "connected" },
  { name: "github-mcp", mode: "http", tools_count: 14, tools: ["get_pr","list_prs","create_review","get_file","list_commits","search_code","get_issue","list_issues","get_repo","list_branches","get_diff","add_comment","get_check_runs","get_workflow_runs"], eager: true, status: "connected" },
  { name: "postgres-mcp", mode: "sse", tools_count: 4, tools: ["query","schema","explain","describe_table"], eager: false, status: "connected" },
  { name: "knowledge-mcp", mode: "http", tools_count: 8, tools: ["search","get_doc","list_collections","embed","upsert","delete","stats","reindex"], eager: false, status: "degraded" },
  { name: "browser-mcp", mode: "stdio", tools_count: 11, tools: ["navigate","click","type","screenshot","get_text","wait","scroll","go_back","go_forward","new_tab","close_tab"], eager: false, status: "disconnected" },
];

export const ERROR_GROUPS: ErrorGroup[] = [
  { error_class: "BudgetExceededError", count_24h: 47, last: "32s ago", top_agent: "audit-emitter" },
  { error_class: "SpawnCycleError", count_24h: 12, last: "1m 17s ago", top_agent: "claim-router" },
  { error_class: "ToolExecutionError", count_24h: 8, last: "4m ago", top_agent: "doc-summarizer" },
  { error_class: "DepthLimitError", count_24h: 3, last: "47m ago", top_agent: "doc-extractor" },
  { error_class: "TrustViolationError", count_24h: 2, last: "1h 12m ago", top_agent: "policy-linter" },
  { error_class: "SpawnCapError", count_24h: 1, last: "3h 8m ago", top_agent: "ingest-router" },
];

export const BURN_RATE: number[] = [
  220, 240, 280, 260, 310, 340, 380, 360, 410, 440, 420, 480,
  510, 540, 510, 580, 620, 600, 660, 690, 720, 700, 760, 810,
  790, 850, 880, 920, 900, 970, 1010, 1040, 1080, 1110, 1090, 1140,
  1180, 1220, 1210, 1260, 1290, 1320, 1310, 1360, 1390, 1420, 1450, 1480,
  1500, 1540, 1570, 1600, 1620, 1660, 1690, 1710, 1740, 1780, 1810, 1840,
];

export const REJECTION_COUNTS: RejectionCounts = {
  budget: 47,
  cycle: 12,
  depth: 3,
  cap: 1,
  timeout: 5,
};

export const RUNTIME: RuntimeInfo = {
  id: "rt-prod-na-7c3a9d",
  broker: "kafka://prod.kafka:9092",
  broker_status: "connected",
  sse_status: "connected",
  spawn_count: 1247,
  max_total_spawns: 5000,
  tokens_used: 168420,
  token_budget: 200000,
  workers_count: 5,
  mcp_count: 5,
};
